name: dart-export
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - astropy=4.0=py37h516909a_1
  - attrs=21.2.0
  - backcall=0.1.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.10.0
  - hdf5=1.10.5
  - hdf5-static=1.10.5
  - hyperion=0.9.10
  - hyperion-fortran=0.9.10
  - icu=64.2
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jpeg=9c
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libstdcxx-ng=9.2.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - llvm-openmp=9.0.1
  - matplotlib=3.2.1
  - mpi=1.0
  - mpich=3.3.2
  - mpmath=1.1.0
  - ncurses=6.1
  - numpy=1.18.1
  - openssl=1.1.1h
  - parso=0.6.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip
  - ply=3.11
  - prompt-toolkit=3.0.4
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - qt=5.12.5
  - readline=8.0
  - scipy=1.7.1
  - setuptools=46.0.0
  - six=1.15.0
  - sqlite=3.30.1
  - sympy=1.5.1
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - wheel=0.34.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - yt=3.5.1
  - zlib=1.2.11
  - pip:
    - fastjsonschema==2.15.1
    - jsonschema==4.1.2
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyrsistent==0.18.0
    - retworkx==0.10.2
    - symengine==0.8.1
    - tweedledum==1.1.1
    - typing-extensions==3.10.0.2
    - zipp==3.6.0

